name: ScheduleReStarter
author: solo
version: 0.0.1
api:
- 2.0.0
- 2.1.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.1.0
main: solo\schedulerestarter\Main
commands:
  재부팅:
    usage: /재부팅
    description: 서버 종료 또는 재부팅 명령어
    permission: schedulerestarter.command.reboot

permissions:
  schedulerestarter.command.reboot:
    default: op