name: SCoin
version: 0.1.1
author: solo
api:
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0
- 3.1.0
- 4.0.0
main: solo\scoin\SCoin
permissions:
  scoin:
    default: op
    children:
      scoin.command:
        default: op
        children:
          scoin.command.allstatus:
            default: true
          scoin.command.coingive:
            default: op
          scoin.command.coinprice:
            default: true
          scoin.command.coinpurchase:
            default: true
          scoin.command.coinsee:
            default: true
          scoin.command.coinsell:
            default: true
          scoin.command.coinset:
            default: op
          scoin.command.cointake:
            default: op
